(begin
  ($include "lib.scm")

  (define (io_ctrl x)
    (ld_a x)
    (out ($word #x2))
  )
  (define (io_wait x)
    (define wait ($def_label))

    ($label wait) 
    (in ($word #x2))
    (nor x)
    (bz wait)
  )
  (define (io_read x y)
    (in x)
    (ld_c y)
    (st_a_@c)
  )
  (define (io_write x y)
    (ld_c x)
    (ld_a_@c)
    (out y)
  )
  (define (wait x)
    (define done ($def_label))
    (define wait ($def_label))
    (define counter ($qword 0))

    (st8_v_@x ($oword 0) counter)
    ($label wait) 
    (add8_@x_v counter x)
    (bc done)
    (bu wait)
    ($label done) 
  )

  (define ($init)
    (define repeat ($def_label))
    (define counter ($qword 8))
    (st_v_@x ($word 0) counter)
    ($label repeat) 

    (add_@x_v counter ($word 1))
    (io_write counter ($word 0))

    (wait ($oword #x4000))
    (bu repeat)
  )
)
