(begin
  (require "lib.scm")

  (define (io_ctrl x)
    (ld_a x)
    (out (lit #x2))
  )
  (define (io_wait x)
    (define wait (label))

    (>> wait) 
    (in (lit #x2))
    (nor x)
    (bz wait)
  )
  (define (io_read x y)
    (in x)
    (ld_c y)
    (st_a_@c)
  )
  (define (io_write x y)
    (ld_c x)
    (ld_a_@c)
    (out y)
  )
  (define (wait x)
    (define done (label))
    (define wait (label))
    (define counter (qlit 0))

    (st8_v_@x (olit 0) counter)
    (>> wait) 
    (add8_@x_v counter x)
    (bc done)
    (bu wait)
    (>> done) 
  )

  (define (__init)
    (define repeat (label))
    (define counter (qlit 8))
    (st_v_@x (lit 0) counter)
    (>> repeat) 

    (add_@x_v counter (lit 1))
    (io_write counter (lit 0))

    (wait (olit #x4000))
    (bu repeat)
  )
)
