(begin
  (require-extension loopy-loop)  
  ($include "lib.scm")
  (define lo_data ($word #x0))
  (define hi_data ($word #x1))
  (define ctrl    ($word #x2))
  
  (define (io_ctrl x)
    (ld_a x)
    (out ctrl)
  )
  (define (io_wait_clr x)
    (define wait ($def_label))

    ($label wait) 
    (in ctrl)
    (nor x)
    (bz wait)
  )
  (define (io_wait_set x)
    (define wait ($def_label))
    (define done ($def_label))

    ($label wait)
    (in ctrl)
    (nor x)
    (bz done)
    (bu wait)
    ($label done)
  )
  (define (io_read x y)
    (in x)
    (ld_c y)
    (st_a_@c)
  )
  (define (io_write x y)
    (ld_c x)
    (ld_a_@c)
    (out y)
  )
  (define (io_write_data x)
    (io_wait_clr ($word #xe))
    (io_write x lo_data)
    (io_write ($off 1 x) hi_data)
    (io_ctrl ($word #x1))
    (io_ctrl ($word #x0))
  )
  (define (io_read_data x)
    (io_ctrl ($word #x2))
    (io_ctrl ($word #x0))
    (io_wait_set ($word #xd))
    (io_read lo_data x)
    (io_read hi_data ($off 1 x))
  )
  (define ($init)
    (define repeat ($def_label))
    (define buffer ($alloc 2))

    (loop ((char <- in-list (string->list "Hello world!\n")))
      (st2_v_@x ($dword (char->integer char)) buffer)
      (io_write_data buffer)
    )
    
    ($label repeat)

    (io_read_data buffer)
    (io_write_data buffer)
    
    (bu repeat)
  )
)
