(begin
  (define (ld_b x)  
    (ld_b0 (// 0 x))
    (ld_b1 (// 1 x))
    (ld_b2 (// 2 x))
    (ld_b3 (// 3 x))
  )
  (define (ld_c x)
    (ld_c0 (// 0 x))
    (ld_c1 (// 1 x))
    (ld_c2 (// 2 x))
    (ld_c3 (// 3 x))
  )

  (define (bu x)
    (ld_b x)
    (bu_b)
  )
  (define (bz x)
    (ld_b x)
    (bz_b)
  )
  (define (bc x)
    (ld_b x)
    (bc_b)
  )

  (define (clc)
    (nor (lit 0))
    (nor (lit 0))
  )
  (define (ld_c_@x x)
    (ld_b x)
    (ld_c0_@b)
    (ld_b0 (++ 1 (// 0 x)))
    (ld_c1_@b)
    (ld_b0 (++ 2 (// 0 x)))
    (ld_c2_@b)
    (ld_b0 (++ 3 (// 0 x)))
    (ld_c3_@b)
  )
  (define (ld_b_@x x)
    (ld_c x)
    (ld_b0_@c)
    (ld_c0 (++ 1 (// 0 x)))
    (ld_b1_@c)
    (ld_c0 (++ 2 (// 0 x)))
    (ld_b2_@c)
    (ld_c0 (++ 3 (// 0 x)))
    (ld_b3_@c)
  )

  (define (st_v_@x v x)
    (ld_c x)
    (ld_a v)
    (st_a_@c)
  )
  (define (st2_v_@x v x)
    (ld_c x)
    (ld_a (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a (// 1 v))
    (st_a_@c)
  )
  (define (st4_v_@x v x)
    (ld_c x)
    (ld_a (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a (// 1 v))
    (st_a_@c)

    (ld_c0 (++ 2 (// 0 x)))
    (ld_a (// 2 v))
    (st_a_@c)

    (ld_c0 (++ 3 (// 0 x)))
    (ld_a (// 3 v))
    (st_a_@c)
  )
  (define (st8_v_@x v x)
    (ld_c x)
    (ld_a (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a (// 1 v))
    (st_a_@c)

    (ld_c0 (++ 2 (// 0 x)))
    (ld_a (// 2 v))
    (st_a_@c)

    (ld_c0 (++ 3 (// 0 x)))
    (ld_a (// 3 v))
    (st_a_@c)

    (ld_c0 (++ 4 (// 0 x)))
    (ld_a (// 4 v))
    (st_a_@c)

    (ld_c0 (++ 5 (// 0 x)))
    (ld_a (// 5 v))
    (st_a_@c)

    (ld_c0 (++ 6 (// 0 x)))
    (ld_a (// 6 v))
    (st_a_@c)

    (ld_c0 (++ 7 (// 0 x)))
    (ld_a (// 7 v))
    (st_a_@c)
  )

  (define (add_@x_v x v)
    (clc)
    (ld_c x)
    (ld_a_@c)
    (add v)
    (st_a_@c)
  )
  (define (add2_@x_v x v)
    (clc)
    (ld_c x)
    (ld_a_@c)
    (add (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a_@c)
    (add (// 1 v))
    (st_a_@c)
  )
  (define (add4_@x_v x v)
    (clc)
    (ld_c x)
    (ld_a_@c)
    (add (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a_@c)
    (add (// 1 v))
    (st_a_@c)

    (ld_c0 (++ 2 (// 0 x)))
    (ld_a_@c)
    (add (// 2 v))
    (st_a_@c)

    (ld_c0 (++ 3 (// 0 x)))
    (ld_a_@c)
    (add (// 3 v))
    (st_a_@c)
  )
  (define (add8_@x_v x v)
    (clc)
    (ld_c x)
    (ld_a_@c)
    (add (// 0 v))
    (st_a_@c)

    (ld_c0 (++ 1 (// 0 x)))
    (ld_a_@c)
    (add (// 1 v))
    (st_a_@c)

    (ld_c0 (++ 2 (// 0 x)))
    (ld_a_@c)
    (add (// 2 v))
    (st_a_@c)

    (ld_c0 (++ 3 (// 0 x)))
    (ld_a_@c)
    (add (// 3 v))
    (st_a_@c)

    (ld_c0 (++ 4 (// 0 x)))
    (ld_a_@c)
    (add (// 4 v))
    (st_a_@c)

    (ld_c0 (++ 5 (// 0 x)))
    (ld_a_@c)
    (add (// 5 v))
    (st_a_@c)

    (ld_c0 (++ 6 (// 0 x)))
    (ld_a_@c)
    (add (// 6 v))
    (st_a_@c)

    (ld_c0 (++ 7 (// 0 x)))
    (ld_a_@c)
    (add (// 7 v))
    (st_a_@c)
  )
)

