(begin
  (define (ld_b x)  
    (ld_b0 (// 0 x))
    (ld_b1 (// 1 x))
    (ld_b2 (// 2 x))
    (ld_b3 (// 3 x))
  )
  (define (ld_c x)
    (ld_c0 (// 0 x))
    (ld_c1 (// 1 x))
    (ld_c2 (// 2 x))
    (ld_c3 (// 3 x))
  )

  (define (bu x)
    (ld_b x)
    (bu_b)
  )
  (define (bz x)
    (ld_b x)
    (bz_b)
  )
  (define (bc x)
    (ld_b x)
    (bc_b)
  )
  (define (ld_c_@x x)
    (ld_b x)
    (ld_c0_@b)
    (ld_b0 (++ 1 (// 0 x)))
    (ld_c1_@b)
    (ld_b0 (++ 2 (// 0 x)))
    (ld_c2_@b)
    (ld_b0 (++ 3 (// 0 x)))
    (ld_c3_@b)
  )
  (define (ld_b_@x x)
    (ld_c x)
    (ld_b0_@c)
    (ld_c0 (++ 1 (// 0 x)))
    (ld_b1_@c)
    (ld_c0 (++ 2 (// 0 x)))
    (ld_b2_@c)
    (ld_c0 (++ 3 (// 0 x)))
    (ld_b3_@c)
  )
)

